name: bird-pam
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.12
  - numpy=1.26
  - pandas=2.2
  - pip
  - pytorch::pytorch=2.2
  - pytorch::torchaudio=2.2
  - pytorch::torchvision=0.17
  - scikit-learn=1.5
  - matplotlib=3.8
  - seaborn=0.13
  - tqdm=4.66
  - pyyaml=6.0
  - pip:
      - librosa==0.10.1
      - soundfile==0.12.1
      - mlflow==2.9.2
      - audiomentations==1.4.0
