name: bird-pam
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - pyyaml
  - jupyter
  - pip
  - pip:
      - torch
      - torchaudio
      - torchvision
      - librosa==0.10.1
      - soundfile==0.12.1
      - mlflow==2.9.2
      - audiomentations==1.4.0
